backend:
  name: github
  # name: test-repo
  repo: samuel-ping/personal-website-v3
  branch: cms
  base_url: https://samuelping.herokuapp.com/

media_folder: 'client/public/assets/'
public_folder: 'assets/'

site_url: https://samuel-ping.github.io/personal-website-v3

collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: 'client/src/content/home.yml'
        fields:
          - label: 'Taglines'
            label_singular: 'Tagline'
            name: 'taglines'
            widget: list
            fields:
              - { label: 'Position', name: 'position', widget: string }
              - { label: 'Place', name: 'place', widget: string }
          - name: 'resume'
            label: 'Resume'
            widget: object
            fields:
              - {
                  label: 'Resume File',
                  name: 'resume-file',
                  widget: 'file',
                  allow_multiple: false,
                }
              - {
                  label: 'Upload Date',
                  name: 'date',
                  widget: 'datetime',
                  date_format: 'MM-DD-YYYY',
                  time_format: false,
                  picker_utc: true,
                  hint: 'Date this resume was last updated.',
                }
          - label: 'Links'
            name: 'links'
            widget: object
            fields:
              - {
                  label: 'GitHub Profile URL',
                  name: 'github',
                  widget: 'string',
                }
              - {
                  label: 'LinkedIn Profile URL',
                  name: 'linkedin',
                  widget: 'string',
                }
              - { label: 'Email Address', name: 'email', widget: 'string' }

      - label: 'About Me Page'
        name: 'about'
        file: 'client/src/content/about.yml'
        fields:
          - { label: 'Profile Picture', name: 'profile-picture', widget: image }
          - { label: 'Description', name: 'description', widget: markdown }

  - name: 'work'
    label: 'Work Experience'
    folder: 'client/src/content/work'
    create: true
    fields:
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Job Title', name: 'job-title', widget: 'string' }
      - {
          label: 'Image Thumbnail',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Start Date',
          name: 'start-date',
          widget: 'datetime',
          date_format: 'MM-YYYY',
          time_format: false,
          picker_utc: true,
        }
      - {
          label: 'End Date',
          name: 'end-date',
          widget: 'datetime',
          date_format: 'MM-YYYY',
          time_format: false,
          picker_utc: true,
          required: false,
        }
      - {
          label: 'Company Website URL',
          name: 'company-url',
          widget: 'string',
          required: false,
        }
      - { label: 'Description', name: 'description', widget: 'markdown' }

  - label: 'Projects'
    label_singular: 'Project'
    name: 'projects'
    description: 'My projects!'
    folder: 'client/src/content/projects'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Image Thumbnail',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Start Date',
          name: 'start-date',
          widget: 'datetime',
          date_format: 'MM-YYYY',
          time_format: false,
          picker_utc: true,
        }
      - {
          label: 'End Date',
          name: 'end-date',
          widget: 'datetime',
          date_format: 'MM-YYYY',
          time_format: false,
          picker_utc: true,
          required: false,
        }
      - { label: 'Repository URL', name: 'repo-url', widget: 'string' }
      - {
          label: 'Live Website URL',
          name: 'website-url',
          widget: 'string',
          required: false,
        }
      - { label: 'Technologies Used', name: 'technologies', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }

  - label: 'Involvement'
    name: 'involvement'
    description: 'Clubs and extracurriculars!'
    folder: 'client/src/content/involvement'
    create: true
    fields:
      - { label: 'Activity', name: 'activity', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - {
          label: 'Image Thumbnail',
          name: 'thumbnail',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Start Date',
          name: 'start-date',
          widget: 'datetime',
          date_format: 'MM-YYYY',
          time_format: false,
          picker_utc: true,
        }
      - {
          label: 'End Date',
          name: 'end-date',
          widget: 'datetime',
          date_format: 'MM-YYYY',
          time_format: false,
          picker_utc: true,
          required: false,
        }
      - {
          label: 'Website URL',
          name: 'website-url',
          widget: 'string',
          required: false,
        }
      - { label: 'Description', name: 'description', widget: 'markdown' }
